[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "your authcode "
email = "your qq email"

[redisConfig]
host = "127.0.0.1"
port = 6380
password = ""
db = 0

[mysqlConfig]
host = "localhost"
port = 3307
user = "root"
password = "root1234"
databaseName = "GopherAI"
# databaseName = "review"
charset = "utf8mb4"

[jwtConfig]
expire_duration = 8760
issuer = "huanheart"
subject = "GopherAI"
key = "GopherAI-v1"

[rabbitmqConfig]
host = "127.0.0.1"
port = 5672
username = "admin"
password = "admin"
vhost = "/"
