[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "tpzhknloealhbjgf"
email = "1691129074@qq.com"

[redisConfig]
host = "127.0.0.1"
port = 6380
password = ""
db = 0

[mysqlConfig]
host = "localhost"
port = 3307
user = "root"
password = "root1234"
databaseName = "GopherAI"
# databaseName = "review"
charset = "utf8mb4"

[jwtConfig]
expire_duration = 8760
issuer = "huanheart"
subject = "GopherAI"
key = "GopherAI-v1"

[rabbitmqConfig]
host = "127.0.0.1"
port = 5672
username = "admin"
password = "admin"
vhost = "/"

[ollamaConfig]
baseURL = "http://localhost:11434"
modelName = "gemma3:4b"

[imageAIConfig]
key = "sk-99ca8180a3c44abbb69909aa9083edc8"
modelname = "qwen3-vl-plus"
baseurl = "https://dashscope.aliyuncs.com/compatible-mode/v1"

[googleConfig]
googleAPIKey = "AIzaSyB45PzQigSxozVA6VjfW9rlA1EtrJ8WvYk"
googleSearchEngineID = "f0f6c8d0d4bef44af"
